/*-GNU-GPL-BEGIN-*
  This program is free software; you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation; either version 2 of the License, or
  (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program; if not, write to the Free Software
  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
*-GNU-GPL-END-*/

/*
  File: Lang_pt_BR.java

  DO NOT EDIT THIS FILE. This is an automatically generated file.
  Changes to this file will be lost.
 */

package jmud.lang;

public class Lang {

  static public final String JMUD_MSG_REQ_PORT = "requer número da porta";
  static public final String JMUD_CMDLINE_VERSION_SWITCH = "-versao";
  static public final String JMUD_MSG_MISSING_CONFIG = "Arquivo de configuração não encontrado: ";
  static public final String JMUD_MSG_LOADING_CONFIG = "Carregando arquivo de configuração: ";
  static public final String JMUD_MSG_REQ_NUM_VALUE = "requer valor numérico";
  static public final String JMUD_MSG_SUBVERSION_READ_ERROR = "Falha ao ler arquivo de subversão: ";
  static public final String JMUD_MSG_USAGE = "Uso: JMud -versao | { [-c <config>] [-p <porta>] [-teste] }";
  static public final String JMUD_MSG_CONFIG_IO_ERROR = "Falha de E/S ao ler arquivo de configuração: ";
  static public final String JMUD_MSG_ABORTING = "Abortando.";
  static public final String JMUD_MSG_REQ_CFG_FILE = "requer arquivo de configuração";
  static public final String JMUD_MSG_DUP_OPT = "Opção duplicada: ";
  static public final String JMUD_MSG_EMPTY_SUBVERSION = "Arquivo de subversão vazio: ";
  static public final String JMUD_LANGUAGE = "Português (Brasil)";
  static public final String JMUD_MSG_INV_OPT = "Opção inválida: ";
  static public final String JMUD_MSG_LANGUAGE = "Idioma: Português (Brasil)";
  static public final String JMUD_MSG_VERSION = "Versão: ";
  static public final String JMUD_CMDLINE_TEST_SWITCH = "-teste";
  static public final String JMUD_MSG_CONFIG_FORMAT_ERROR = "Formato inválido do arquivo de configuração: ";
  static public final String JMUD_MSG_SUBVERSION_UNDEF_ERROR = "Arquivo de subversão não definido";
  static public final String JMUD_MSG_SUBVERSION_OPEN_ERROR = "Falha ao abrir arquivo de subversão: ";
  static public final String JMUD_MSG_ERROR = "JMud: Erro: ";

}

/*
  File: Lang_pt_BR.java

  DO NOT EDIT THIS FILE. This is an automatically generated file.
  Changes to this file will be lost.
*/
