
//----------------------------------------------------
// The following code was generated by CUP v0.10j
// Tue Oct 30 22:48:46 GMT-02:00 2001
//----------------------------------------------------

package jmud.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TK_SCOLON = 11;
  public static final int TK_RPAR = 7;
  public static final int TK_EQ = 6;
  public static final int TK_LBRA = 10;
  public static final int EOF = 0;
  public static final int TK_LPAR = 8;
  public static final int TK_NUMBER = 4;
  public static final int TK_ILLEGAL = 2;
  public static final int error = 1;
  public static final int TK_STRING = 5;
  public static final int TK_RBRA = 9;
  public static final int TK_IDENT = 3;
}

